### ISSUE TITLE
前端项目打包出来的dist放在Nginx上运行，服务器500错误

### ISSUE THREAD

**Issue by EGOISTW** [smallsnail-wh/interest#1]
想试着模拟一下生产环境，但是打包出来的dist文件夹与标准的项目的结构完全不同，也没有index.html，直接在Nginx上跑就500错误了

**Comment by smallsnail-wh** [comment]
npm run build后，会生成dist文件夹和index_prod.html文件，将这两个文件拿出来，配置到nginx中就ok了
