### ISSUE TITLE
sudo npm run init报错

### ISSUE THREAD

**Issue by allenz92** [smallsnail-wh/interest#13]
![image](https://user-images.githubusercontent.com/20952145/49984966-2b8abf00-ffa5-11e8-8bf8-7a2bbcc194e5.png)

**Comment by smallsnail-wh** [comment]
不要run init了，直接run dev。还有看一下https://github.com/Big-Chinese-Cabbage/interest/tree/master/interest-web 启动报错解决方法第二点。
