### ISSUE TITLE
Full authentication is required to access this resource

### ISSUE THREAD

**Issue by xutingyin** [smallsnail-wh/interest#14]
server 启动后：
http://localhost:8080/interest/ 访问，页面报这个错
Full authentication is required to access this resource
 
另外请问有没有部署教程，redis如何在此项目中使用

**Comment by smallsnail-wh** [comment]
README.md中有说，前后端都需要启动，redis目前主要是用来存储token的。

**Comment by xutingyin** [comment]
非常感谢，已经启动起来了 : )
