### ISSUE TITLE
 Invalid options in vue.config.js: "publicPath" is not allowed

### ISSUE THREAD

**Issue by dianbaiyizhong** [smallsnail-wh/interest#17]
ERROR  Invalid options in vue.config.js: "publicPath" is not allowed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insterest-web@0.1.0 serve: `vue-cli-service serve --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the insterest-web@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\3092\AppData\Roaming\npm-cache\_logs\2019-01-14T01_59_23_728Z-debug.log

**Comment by smallsnail-wh** [comment]
你把vue.config.js中的publicPath改成baseUrl试试。

**Comment by dianbaiyizhong** [comment]
修改了baseUrl后，继续出现错误


 INFO  Starting development server...
 94% after seal

 ERROR  Failed to compile with 1 errors                                                                         12:45:11

This relative module was not found:

**Comment by smallsnail-wh** [comment]
你install报错了吧，缺少module好像

**Comment by dianbaiyizhong** [comment]
![_20190114151629](https://user-images.githubusercontent.com/11265013/51100101-6e8fba80-180f-11e9-9858-143a3e7de039.png)

**Comment by dianbaiyizhong** [comment]
install没问题啊

**Comment by dkrg520** [comment]
作者犯了个错误，main.js中这个配置import App from "./App.vue"应改为import App from "./app.vue;
大小写的问题。

**Comment by dianbaiyizhong** [comment]
> 作者犯了个错误，main.js中这个配置import App from "./App.vue"应改为import App from "./app.vue;
> 大小写的问题。

我晕。。没跑起来，作者是怎么敢提交代码的

**Comment by dkrg520** [comment]
改了还不行么？

**Comment by smallsnail-wh** [comment]
> > 作者犯了个错误，main.js中这个配置导入应用程序来自“./App.vue”应改为导入应用程序来自“./app.vue; 
> > 大小写的问题。
> 
> 我晕..没跑起来，作者是怎么敢提交代码的

你这话说的，我自己没跑起来可能放吗？我现在服务器上的就是最新代码。
![image](https://user-images.githubusercontent.com/30545965/51105184-44e08e80-1823-11e9-9b26-6a9d5d47af48.png)

**Comment by smallsnail-wh** [comment]
> 作者犯了个错误，main.js中这个配置导入应用程序来自“./App.vue”应改为导入应用程序来自“./app.vue; 
> 大小写的问题。

应该不是这个错吧。我入口就是App.vue不是app.vue.

**Comment by dkrg520** [comment]
> > 作者犯了个错误，main.js中这个配置导入应用程序来自“./App.vue”应改为导入应用程序来自“./app.vue; 
> > 大小写的问题。
> 
> 应该不是这个错吧。我入口就是App.vue不是app.vue。
就是这个问题，我改了后就可以登录了。我下下来的文件里命名是小写，但是你配置里的文件用的是大写。

**Comment by smallsnail-wh** [comment]
感谢提醒，我本地是App.vue,然后我查了一下git默认是不区分大小写的，尴尬
