### ISSUE TITLE
说几个问题

### ISSUE THREAD

**Issue by stinchan** [smallsnail-wh/interest#18]
【前端-vuecli3.0版本】：
1、vue.config.js文件中，不能用publicPath，会报错，改为baseUrl
module.exports = {
  // 基本路径
  baseUrl: "/",
2、main.js 引入有问题。这个需要改为小写的./app.vue
import App from "./App.vue";
【后端】：
1、升级后的版本返回值，都用了ResponseWrapper包装，会在json值里增加data这个节点，前端页面显示也需要跟着改变。不然页面展示不出来（后台管理菜单）。
MenuController示例：
升级前：
	@GetMapping("/manage/menu")
	public List<MenuEntity> menuList() {
		List<MenuEntity> menuList = menuService.menuList(SecurityAuthenUtil.getId());
		return menuList;
	}
升级后：
    @GetMapping("/manage/menu")
    public ResponseWrapper<List<MenuEntity>> menuList() {
        List<MenuEntity> menuList = menuService.menuList(SecurityAuthenUtil.getId());
        return new ResponseWrapper<>(menuList);
    }
2、安全配置类用户密码加密由md5加密改为BCrypt加密，这里代码需要修改：
WebsecurityConfig：
原代码：
	@Autowired
	public void globalUserDetails(AuthenticationManagerBuilder auth) throws Exception {
		auth.userDetailsService(userDetailsService);
	}
需改为：
	@Autowired
	public void globalUserDetails(AuthenticationManagerBuilder auth) throws Exception {
		auth.userDetailsService(userDetailsService).passwordEncoder(new BCryptPasswordEncoder());;
	}
【脚本】
sys_user表，admin初始的账户密码不对。大家可以自己使用BCryptPasswordEncoder类，encode一个自己的密码。

**Comment by smallsnail-wh** [comment]
感谢你提出的问题。
1. **_vue.config.js文件中，不能用publicPath，会报错，改为baseUrl_** 这个问题很奇怪，vue官方文档中给出，vue-cli 3.0 使用publicPath代替了baseUrl。我这边如果使用baseUrl日志会给我警告，让我换成publicPath。
2. **_main.js 引入有问题。这个需要改为小写的./app.vue import App from "./App.vue";_** 这个问题以修复，因为git默认对大小写不明感。
3. 后端问题1，修复。
4. 后端问题2，这个我这边是没问题的，因为Spring security5默认是BCrypt加密，不知道什么原因导致你那边不同，有待探讨。
5. sql脚本，我这边也是没问题的。

**Comment by chenhp123** [comment]
提的问题非常棒，基本指出了运行出现的问题
