### ISSUE TITLE
请问是如何配置Spring security用户登陆的加密密码进行匹配的？

### ISSUE THREAD

**Issue by EGOISTW** [smallsnail-wh/interest#2]
我看到作者在用户注册与更新时都对密码进行了BCrypt加密处理，但没有在WebsecurityConfig中发现用户登陆的passwordEncoder相关配置,依然可以登录成功，所以想请问一下是在哪里做了用户登录加密算法的相关配置。

**Comment by smallsnail-wh** [comment]
spring security5默认BCrypt加密，相关配置你可以百度或者看官方文档
