### ISSUE TITLE
项目介绍和公告栏的前端vue组件代码没有找到。

### ISSUE THREAD

**Issue by kancve** [smallsnail-wh/interest#44]
向伟大的开源者致敬！
我将interest-web重新编译并将baseURL指定到 "https://www.lovemtt.com/interest，显示的效果和你的却不一样，详情如附图。
再次感谢。
![1](https://user-images.githubusercontent.com/29945891/87842545-c6652100-c8df-11ea-9c1d-daf73225646c.png)

**Comment by smallsnail-wh** [comment]
github上的事iview版本
