### ISSUE TITLE
没能跑起来

### ISSUE THREAD

**Issue by SHEN-XM** [smallsnail-wh/interest#5]
![screen shot 2018-09-28 at 4 35 17 pm](https://user-images.githubusercontent.com/30321653/46197481-93355480-c33c-11e8-837c-c44da98d7bd8.png)

**Comment by smallsnail-wh** [comment]
换cnpm试试

**Comment by Cecilia520** [comment]
C:\Apps\idea\IntelliJIDEA\bin\runnerw.exe C:\Apps\nodeJS\node.exe C:\Apps\nodeJS\node_modules\npm\bin\npm-cli.js run dev --scripts-prepend-node-path=auto

> interest-web@1.0.0 dev D:\documents\Codes\ML\interest\interest-web
> webpack-dev-server --content-base ./ --open --inline --hot --host 0.0.0.0 --compress --history-api-fallback --config webpack.dev.config.js

'webpack-dev-server' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Apps\\nodeJS\\node.exe" "C:\\Apps\\nodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev" "--scripts-prepend-node-path=auto"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! interest-web@1.0.0 dev: `webpack-dev-server --content-base ./ --open --inline --hot --host 0.0.0.0 --compress --history-api-fallback --config webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the interest-web@1.0.0 dev script 'webpack-dev-server --content-base ./ --open --inline --hot --host 0.0.0.0 --compress --history-api-fallback --config webpack.dev.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the interest-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --content-base ./ --open --inline --hot --host 0.0.0.0 --compress --history-api-fallback --config webpack.dev.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs interest-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls interest-web
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\documents\Codes\ML\interest\interest-web\npm-debug.log

Process finished with exit code 1

**Comment by Cecilia520** [comment]
@smallsnail-wh 出现了以下问题，，构建失败，没有正确跑起来！

**Comment by smallsnail-wh** [comment]
Make sure you have the latest version of node.js and npm installed.
更新一下你node.js
