### ISSUE TITLE
关于github登录部分后台相关

### ISSUE THREAD

**Issue by AnshayM** [smallsnail-wh/interest#6]
我在看你后代码时，发现里面CLIENT_ID和CLIENT_SECRET 都是空的，可是要获取token是需要这两个参数的，所以不太理解。
我猜想这里之前写了但是要公布代码去掉了，信息改成从数据库获取，那么是在哪个地方从数据库获取的呢？或者是通过什么其他方法吗？

**Comment by smallsnail-wh** [comment]
大兄弟，CLIENT_ID和CLIENT_SECRET 是我去掉的，那是我的，你需要自己在github上申请一个，然后填上去

**Comment by AnshayM** [comment]
我这边运行你的项目时，用我的github登录，是可以在页面上正确显示头像和姓名的，所以我不太理解。
官方接口里要传上面两个参数才可以获取token，根据token才可以查询用户的信息，不知道这里你是怎么做到的，请问可否点拨一二？

**Comment by smallsnail-wh** [comment]
当用户确认github登录后，github会重定向我github中设置的Authorization callback URL，也就是我的网页，同时也会把我需要的Authorization code传过来，然后我在页面中会解析url得到Authorization code，然后请求后端接口，把Authorization code传到后端，后端再使用Authorization code来向github请求access token，得到access token后，再用access token来请求github的用户信息。

**Comment by AnshayM** [comment]
我的意思是，我这里下载你的项目里面后台是没有CLIENT_ID和CLIENT_SECRET 的，但是运行起来依然获取到了用户头像和name。所以不理解。

**Comment by smallsnail-wh** [comment]
你本地前后端启动后，点击github登录后，是不是会跳到我的网站？

**Comment by AnshayM** [comment]
我突然明白了什么，对不起是我太笨了。
点击链接了之后，请求的后台就不是本地的后台了，而是远程服务器。所以本地的代码只是在帐号密码登录的时候适用。
叨扰大佬这么久，麻烦了，谢谢耐心解答。

**Comment by xiaoba28** [comment]
为啥我使用GitHub登录后  没有控制台  进不去页面呀
