### ISSUE TITLE
奇怪 ，我运行起来登录弹出对话框

### ISSUE THREAD

**Issue by nightkidfifa** [smallsnail-wh/interest#7]
![tim 20181108161454](https://user-images.githubusercontent.com/3062753/48185927-7cd5dc00-e371-11e8-99ae-8e68a58de363.jpg)

**Comment by smallsnail-wh** [comment]
前端出现这种情况都是你的后端没有配置好，看一下https://github.com/smallsnail-wh/interest/tree/master/interest-server
